#!/usr/bin/env python3

import argparse
import sys
import os
from .graph import PangenomeGraph
from .logger import setup_logger
from .walk_variants import process_haplotype_variants
import click
from .dfs import dfs_methods

@click.group(context_settings={"help_option_names": ["-h", "--help"]})
def cli():
    """pantree: pangenome graph to VCF conversion tools"""
    pass

@cli.command(name='gfa2vcf', context_settings={"help_option_names": ["-h", "--help"]})
@click.argument("gfa_file")
@click.argument("vcf_file")
@click.option("--chr-id", "-c", default="chr0", help="Chromosome ID for VCF output")
@click.option("--ref-name", "-r", default="GRCh38", help="Reference sample name")
@click.option("--no-genotypes", is_flag=True, help="Do not put genotypes in VCF")
@click.option("--log-path", default=None, help="Path to log file")
@click.option("--verbose", "-v", is_flag=True, help="Print log statements to console")
@click.option("--dfs-method", default="max_weight", type=click.Choice(dfs_methods.keys()),
              help="DFS method for tree construction")
@click.option("--priority-samples", default=None,
    help="Comma-separated list of sample names along which to compute variant positions; "
         "if dfs-method is 'contiguous', these are prioritized when building the DFS tree "
         "in the order they are provided")
@click.option("--no-missingness", is_flag=True,
    help="Skip missingness computation for genotypes. Use this for graphs generated by vg, "
         "where the missingness logic may fail due to how vg handles linear reference genomes")
def gfa2vcf(gfa_file, vcf_file, chr_id, ref_name, no_genotypes, log_path, verbose, dfs_method, priority_samples, no_missingness):
    """Convert GFA pangenome graph to VCF format"""
    # Set up logger
    logger = setup_logger(log_path=log_path, verbose=verbose) if (log_path or verbose) else None

    # Convert dfs_method string to function
    dfs_method_func = dfs_methods[dfs_method]

    if logger:
        logger.info(f"pantree CLI invoked")
        logger.info(f"Input GFA: {gfa_file}")
        logger.info(f"Output VCF: {vcf_file}")
        msg = (f"Parameters: chr_id={chr_id}, ref_name={ref_name}, no_genotypes={no_genotypes}, "
               f"dfs_method={dfs_method}, priority_samples={priority_samples}, no_missingness={no_missingness}")
        logger.info(msg)
    # Check if input file exists
    if not os.path.exists(gfa_file):
        print(f"Error: GFA file '{gfa_file}' not found", file=sys.stderr)
        sys.exit(1)

    # Haplotype priorities for DFS
    priority_dict = None
    if priority_samples:
        sample_list = [s.strip() for s in priority_samples.split(',')]
        priority_dict = {sample: i for i, sample in enumerate(sample_list)}
        if logger:
            logger.info(f"Priority dict: {priority_dict}")

    # Load the graph
    G = PangenomeGraph.from_gfa(
        gfa_file,
        ref_name=ref_name,
        logger=logger,
        dfs_method=dfs_method_func,
        priority_dict=priority_dict
    )

    # Generate VCF
    if no_genotypes:
        G.write_vcf(None, vcf_file, chr_id, no_missingness=no_missingness)
    else:
        G.write_vcf(gfa_file, vcf_file, chr_id, no_missingness=no_missingness)

    if logger:
        logger.info(f"Wrote VCF file: {vcf_file}")
    else:
        print(f"Wrote VCF file: {vcf_file}")

@cli.command(name='consolidate', context_settings={"help_option_names": ["-h", "--help"]})
@click.argument("input_vcf")
@click.argument("sample_name")
@click.argument("haplotype_number", type=int)
@click.argument("output_vcf")
def consolidate_cmd(input_vcf, sample_name, haplotype_number, output_vcf):
    """Consolidate overlapping variants for a specific haplotype.

    INPUT_VCF: Path to input VCF file

    SAMPLE_NAME: Name of the sample to analyze

    HAPLOTYPE_NUMBER: Which haplotype to use (0 or 1 for diploid)

    OUTPUT_VCF: Path to write output VCF file
    """
    if not os.path.exists(input_vcf):
        print(f"Error: VCF file '{input_vcf}' not found", file=sys.stderr)
        sys.exit(1)

    process_haplotype_variants(input_vcf, sample_name, haplotype_number, output_vcf)
    print(f"Wrote consolidated VCF file: {output_vcf}")

def main():
    """Backward compatibility wrapper for pantree CLI"""
    import sys
    # If called as 'pantree' with arguments, assume gfa2vcf
    if len(sys.argv) > 1 and not sys.argv[1].startswith('-') and sys.argv[1] not in ['gfa2vcf', 'consolidate']:
        sys.argv.insert(1, 'gfa2vcf')
    cli()

if __name__ == "__main__":
    cli()
